import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import translations from "./assets/locales/translations.json"
import { useRouter } from "next/router"
import homeCover from "./assets/images/mantalena-bafiti-villa-cover.jpg"
import mant from "./assets/images/mantalena-bafiti-architect-engineer-paros-greece.jpg"
import projects from "./assets/projects/projects.json";
import logo from "./assets/images/paros-architecture-architect-mantalena-bafiti-new.svg"
import EmblaCarousel from "./Components/Carousel"

const basePath = "/images"

export default function Home() {
  const { locale, locales, asPath } = useRouter()

  return (
    <div>
      <Head>
        <title>{translations[locale].home_title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div id="homeContainer">
        <div className={styles.row}>
          <div className={styles.col_50}>
            <div className={styles.text__box}>
            <div id="logo" className={styles.logo}>
                    <img src={logo.src} alt={translations[locale].logo_alt} />
                    <h1 className={styles.title}><span>MANTALENA</span><br/><span>BAFITI</span><br/><span>ARCHITECT</span></h1>
              </div>
              <p className={styles.paragraph}>We create, you enjoy!</p>
              <a className={styles.button} href="#projects">View Our Projects</a>
            </div>
          </div>
          <div className={styles.col_50}>
            <img src={homeCover.src} alt="" />
          </div>
        </div>
      </div>

      <div id="projects">
        <h3>Projects</h3>
        <div className={styles.projects}>
          {projects.projects.map(proj => {
            return <div key={proj} className={styles.project}>
              <div className={styles.project_box}>
                <EmblaCarousel slides={proj.gallery} />
              </div>
              <div className={styles.project_info}>
                <h4>{locale == "en" ? proj.title_en : proj.title_el}</h4>
                <span>{locale == "en" ? proj.caption_en : proj.caption_el}</span>
              </div>
              </div>
          })}
          
        </div>
      </div>
      <div className={styles.separator}></div>

      <div id="about_container">
        <div className={styles.aboutInner}>
            <div className={styles.row}>
              <div id="about" className={[styles.col_50, styles.pp].join(" ")}>
                <h1 className={styles.aboutTitle}>Mantalena Bafiti</h1>
                <p className={styles.aboutText}>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                            </p>
                </div>
                <div className={styles.col_50}>
                <img src={mant.src} alt="" />
                </div>
            </div>
        </div>
      </div>

    </div>
  )
}
